package autocode

type RouterGroup struct {
	// Code generated by github.com/liujianjiang/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	// Code generated by github.com/liujianjiang/gin-vue-admin/server End; DO NOT EDIT.
}
